FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends gcc && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD celery -A app.tasks.celery_app worker \
     --concurrency=${WORKER_CONCURRENCY:-4} \
     --loglevel=info \
     --time-limit=3600 \
     --soft-time-limit=3300
